algoritmo "semnome"
// Escreva um algoritmo no visualG, que leia dois valores reais e mostra a soma,
// a subtração, a multiplicação e a divisão
//destes dois valores.


var
numero_um:inteiro
numero_dois:inteiro
soma:inteiro


inicio
Escreval("Digite o primeiro número: ")
leia(numero_um)
Escreval("Digite o segundo número: ")
leia(numero_dois)
soma <- numero_um + numero_dois
Escreval("A sua soma entre esses números é de: " ,numero_um, "+" ,numero_dois,
"=" ,soma)




fimalgoritmo
